name: timberr
description: A furniture shopping app made using Flutter, Firebase and Getx state management

publish_to: 'none'

version: 1.9.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  supabase_flutter: ^0.2.12
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  lottie: ^1.2.1
  url_launcher: ^6.0.18
  image_picker: ^0.8.4+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/lottie/
  - assets/fonts/

  fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans_Regular.ttf
      - asset: assets/fonts/NunitoSans_Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans_Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans_ExtraBold.ttf
        weight: 800

  - family: Gelasio
    fonts:
      - asset: assets/fonts/Gelasio_Regular.ttf
      - asset: assets/fonts/Gelasio_Medium.ttf
        weight: 500
      - asset: assets/fonts/Gelasio_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Gelasio_Bold.ttf
        weight: 700

  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather_Regular.ttf
      - asset: assets/fonts/Merriweather_Bold.ttf
        weight: 700

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
