name: timberr
description: A furniture shopping app made using Flutter, Firebase and Getx state management

publish_to: 'none'

version: 1.7.5+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.2.0
  get: ^4.6.1
  supabase_flutter: ^0.2.11
  flutter_svg: ^1.0.1
  cached_network_image: ^3.2.0
  lottie: ^1.2.1
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
